/**
 * Onboard a cluster through the console, then hang its agent and ask the
 * platform what it can see.
 *
 * Two flows found the worst defects of their session and neither was in CI:
 *
 *   - **The lease was never renewed.** The claim recorded `worker_identity()`
 *     and the watchdog renewed with an empty `settings.worker_id`, so every
 *     distributed investigation longer than its lease was reaped as a dead
 *     worker while the worker was still running it. An investigation normally
 *     takes a second; only a slow one shows it, and a hung agent makes a slow
 *     one on demand — each wave waits its full collection budget.
 *   - **A hung agent looked healthy, then vanished**, because presence records
 *     carried liveness computed when written, and the explanation for its
 *     empty investigation told the operator to check a kubeconfig that is not
 *     in the path.
 *
 * Nothing here is simulated. The manifest is the one the console hands a person
 * — read off the page, not generated by this script — and the hang is
 * `kill -STOP` on the agent process inside the kind node, which keeps its
 * stream open while nothing on it answers. That is the unclean failure: a
 * clean shutdown closes the socket and every part of the platform already
 * handles it.
 *
 * Asserted:
 *   1. the enrolment the console creates can be applied, and the page reports
 *      the agent connected
 *   2. once the agent is frozen, the console shows it as silent
 *   3. an investigation of its cluster is **not reaped** — it outlives its
 *      lease by design — and ends with the agent diagnosis, through the agent
 *
 * Refused (exit 2) rather than passed when the precondition for a check never
 * held: no manifest on the page, an agent that never connected, a process that
 * could not be found to freeze, an investigation that attempted no reads.
 *
 * Usage (see scripts/integration_verify.sh for CI):
 *
 *   CONSOLE_URL=http://localhost:3000 API_URL=http://127.0.0.1:8000 \
 *   CONSOLE_TOKEN=<admin token> AGENT_IMAGE=k8s-ops-agent:local \
 *   KUBECTL="kubectl --context kind-dev" NODE_CONTAINER=dev-control-plane \
 *   node scripts/agent_journey.mjs
 *
 * Exit 0 clean, 1 findings, 2 the run could not be trusted.
 */

import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const BASE = process.env.CONSOLE_URL || "http://localhost:3000";
const API = process.env.API_URL || "http://127.0.0.1:8000";
const CDP = process.env.CDP_URL || "http://127.0.0.1:9222";
const TOKEN = process.env.CONSOLE_TOKEN || "";
const IMAGE = process.env.AGENT_IMAGE || "";
const KUBECTL = process.env.KUBECTL || "kubectl";
const NODE = process.env.NODE_CONTAINER || "";
const CLUSTER = `journey-${Date.now().toString(36)}`;
const NAMESPACE = "k8s-ops-agent";

// The platform's own marker for a reaped job. Matching its words rather than a
// status is deliberate: `failed` is also the *correct* outcome here, because a
// frozen agent collects nothing usable. What must not happen is failing *as a
// dead worker*.
const REAPED = /worker stopped before the run finished/i;
const DIAGNOSED = /not answering/i;

const findings = [];
const refusals = [];
const note = (line) => console.log(`  ${line}`);
const sh = (command) =>
  execSync(command, { encoding: "utf8", stdio: ["pipe", "pipe", "pipe"] });
const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

if (!TOKEN || !IMAGE || !NODE) {
  console.error(
    "agent_journey needs CONSOLE_TOKEN, AGENT_IMAGE and NODE_CONTAINER.",
  );
  process.exit(2);
}

/* ------------------------------------------------------------------ CDP -- */

const target = await (
  await fetch(`${CDP}/json/new?about:blank`, { method: "PUT" })
).json();
const ws = new WebSocket(target.webSocketDebuggerUrl);
let nextId = 0;
const pending = new Map();
ws.addEventListener("message", (event) => {
  const message = JSON.parse(event.data);
  if (message.id && pending.has(message.id)) {
    pending.get(message.id)(message.result);
    pending.delete(message.id);
  }
});
await new Promise((resolve) => ws.addEventListener("open", resolve));
const send = (method, params = {}) =>
  new Promise((resolve) => {
    const id = ++nextId;
    pending.set(id, resolve);
    ws.send(JSON.stringify({ id, method, params }));
  });
const evaluate = async (expression) =>
  (
    await send("Runtime.evaluate", {
      expression,
      awaitPromise: true,
      returnByValue: true,
    })
  )?.result?.value;
await send("Page.enable");
await send("Runtime.enable");

const api = async (path, init = {}) =>
  fetch(`${API}${path}`, {
    ...init,
    headers: {
      Authorization: `Bearer ${TOKEN}`,
      "Content-Type": "application/json",
      ...(init.headers || {}),
    },
  });

let frozenPid = "";

async function main() {
  console.log(
    `\nOnboarding ${CLUSTER} through ${BASE}, then hanging its agent\n`,
  );

  // Sign-in through the form is the console journey's job; here the gate is
  // only in the way.
  await send("Page.navigate", { url: BASE });
  await wait(1200);
  await evaluate(
    `sessionStorage.setItem("k8s-agent-token", ${JSON.stringify(TOKEN)})`,
  );

  // A clean slate. The enrolment manifest names a fixed namespace, and an agent
  // left there by an earlier leg would load its old identity from the Secret
  // instead of enrolling with the token this run is testing.
  sh(
    `${KUBECTL} delete namespace ${NAMESPACE} --ignore-not-found --wait=true --timeout=120s`,
  );

  // --- 1. Enrol through the page, apply what it hands you ---------------------
  await send("Page.navigate", { url: `${BASE}/connect` });
  await wait(2500);
  await evaluate(`(() => {
    const input = document.querySelector("input");
    const set = Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, "value").set;
    set.call(input, ${JSON.stringify(CLUSTER)});
    input.dispatchEvent(new Event("input", { bubbles: true }));
    [...document.querySelectorAll("button")].find((b) => /^Create enrolment$/.test(b.textContent.trim())).click();
  })()`);
  await wait(3000);

  const manifest = await evaluate(
    `[...document.querySelectorAll("pre")].map((p) => p.innerText).find((t) => /kind: Deployment/.test(t)) || ""`,
  );
  if (!manifest) {
    refusals.push(
      "the console showed no manifest after creating an enrolment, so there was nothing to apply.",
    );
    return;
  }
  // Only the image changes: the manifest names a published tag a kind cluster
  // cannot pull from a local build.
  const patched = manifest.replace(
    /image: \S*k8s-ops-agent\S*/,
    `image: ${IMAGE}\n          imagePullPolicy: Never`,
  );
  const file = join(tmpdir(), `${CLUSTER}.yaml`);
  writeFileSync(file, patched);
  sh(`${KUBECTL} apply -f ${file}`);
  note(
    `applied the manifest from the page (${(manifest.match(/^kind:/gm) || []).length} objects)`,
  );

  let connected = false;
  for (let i = 0; i < 60 && !connected; i++) {
    await wait(2000);
    connected = Boolean(
      await evaluate(
        `/is connected and answering/.test(document.body.innerText)`,
      ),
    );
  }
  if (!connected) {
    let rollout = "";
    try {
      rollout = sh(`${KUBECTL} -n ${NAMESPACE} get pods -o wide`);
    } catch (error) {
      rollout = String(error.message);
    }
    refusals.push(
      `the agent never reported connected on the page within 120s, so nothing about a hung ` +
        `agent can be observed. Pods:\n${rollout}`,
    );
    return;
  }
  note("the page reported the agent connected and answering");

  // --- 2. Freeze it, and read the console -------------------------------------
  // Let a heartbeat land first, so silence is measured from a fresh record.
  await wait(16000);
  frozenPid = sh(
    `docker exec ${NODE} sh -c 'ps -eo pid,args | grep -v grep | grep -- "--cluster=${CLUSTER}"' | awk '{print $1}' | head -1`,
  ).trim();
  if (!frozenPid) {
    refusals.push(
      `could not find the agent process for ${CLUSTER} in ${NODE} to freeze.`,
    );
    return;
  }
  sh(`docker exec ${NODE} kill -STOP ${frozenPid}`);
  note(`froze the agent (pid ${frozenPid}): stream open, nothing answering`);

  const submitted = await (
    await api("/investigations", {
      method: "POST",
      body: JSON.stringify({ context: CLUSTER, refresh: true }),
    })
  ).json();
  const jobId = submitted.id;

  let silent = "";
  for (let i = 0; i < 20 && !silent; i++) {
    await send("Page.navigate", { url: `${BASE}/settings` });
    await wait(2500);
    silent =
      (await evaluate(
        `(document.body.innerText.match(/Agent silent for \\d+s/) || [""])[0]`,
      )) || "";
  }
  if (silent) {
    note(`the console showed "${silent}"`);
  } else {
    findings.push(
      "the console never showed the frozen agent as silent within 50s. On a multi-worker " +
        "deployment presence records carried liveness computed when written, and staleness " +
        "equalled the record's TTL, so a hung agent read online until it vanished.",
    );
  }

  // --- 3. The investigation outlives its lease and says why it saw nothing ---
  let job = {};
  for (let i = 0; i < 120; i++) {
    job = await (await api(`/investigations/${jobId}`)).json();
    if (["succeeded", "failed", "cancelled"].includes(job.status)) break;
    await wait(3000);
  }
  const result = job.result || job;
  const investigation = result.investigation || {};
  const coverage = investigation.evidence_coverage || {};
  const error = String(job.error || "");

  if (!["succeeded", "failed", "cancelled"].includes(job.status)) {
    refusals.push(
      `the investigation of ${CLUSTER} did not finish within 6 minutes (status ${job.status}).`,
    );
    return;
  }
  if (REAPED.test(error)) {
    findings.push(
      `the investigation was reaped as a dead worker ("${error}") while its worker was running ` +
        `it. Its runtime is two full collection budgets, longer than the lease, so the lease ` +
        `must have been renewed — and was not.`,
    );
    return;
  }
  if (!coverage.total) {
    refusals.push(
      `the investigation recorded no evidence at all (${JSON.stringify(coverage)}), so there is ` +
        `no diagnosis to judge.`,
    );
    return;
  }
  if ((investigation.cluster_access || {}).provider !== "agent") {
    findings.push(
      `the investigation of an agent-only cluster reports cluster_access ` +
        `${JSON.stringify(investigation.cluster_access)}, not the agent.`,
    );
  }
  if (!DIAGNOSED.test(error)) {
    findings.push(
      `a cluster whose agent answered nothing was explained as: "${error}". Every read timed out ` +
        `through the agent (${JSON.stringify(coverage.by_status)}); the message must name the agent.`,
    );
  } else {
    note(
      `not reaped; ended with the agent diagnosis — ${JSON.stringify(coverage.by_status)}`,
    );
  }
}

try {
  await main();
} catch (error) {
  refusals.push(`the journey could not run: ${error.message}`);
} finally {
  if (frozenPid) {
    try {
      sh(`docker exec ${NODE} kill -CONT ${frozenPid}`);
    } catch {
      /* the pod may already be gone */
    }
  }
  try {
    sh(
      `${KUBECTL} delete namespace ${NAMESPACE} --ignore-not-found --wait=false`,
    );
  } catch {
    /* best effort */
  }
  ws.close();
}

console.log("");
for (const finding of findings) console.log(`FAIL  ${finding}\n`);
for (const refusal of refusals) console.log(`REFUSED  ${refusal}\n`);
console.log(
  `agent journey: ${findings.length} finding(s), ${refusals.length} refusal(s)`,
);
process.exit(refusals.length ? 2 : findings.length ? 1 : 0);
